### ISSUE TITLE
Inventories don't save when kicked from a server restart

### ISSUE THREAD

**Issue by nomadjimbob** [Drustcraft/Drustcraft-Engine#29]
### Describe the bug

Player inventories are not saved when the player is online but kicked due to a server restart. After the restart, the players inventory is reverted to the last saved version

### To Reproduce

Stay online, restart the server so the player is kicked

### Expected behaviour

Players inventory to be saved on server kick

### Client Version and Platform

1.17.1

**Comment by lstone01** [comment]
screenshots/videos you want one?

**Comment by nomadjimbob** [comment]
I think its fine. It happened to me. I think the issue is that https://github.com/Drustcraft/Drustcraft-Engine/blob/902e14b6bd23d7eeb560a49c0843f3837e204cc1/Denizen/scripts/player_inventories.dsc#L27 is not being called on shutdown. Might need to test if `on player kicked` is called in this scenario and use that event to save the inventory

**Comment by nomadjimbob** [comment]
I also wonder if `on player quits` is called if someone is kicked using `/kick`?

**Comment by lstone01** [comment]
Is there a way to see?

**Comment by nomadjimbob** [comment]
`on player quits` is called when manually kicked from the server. The solution may be a periodical save.

Maybe players need a 'dirty' flag that is set to true when they login and then set to false when they logout. That way whatever players have a true dirty flag at startup did not have their inventories saved last restart?

**Comment by nomadjimbob** [comment]
Tested and confirmed fixed in 1.0
